root: true
parser: 'babel-eslint'
parserOptions:
  ecmaVersion: 2017
  sourceType: 'module'
  ecmaFeatures:
    experimentalObjectRestSpread: true
extends: ['eslint-config-airbnb']
rules:
  'global-require': 0
  'strict': 0
  'comma-dangle': 0
